#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Validate a FreeQ peer.env exchange file.

Usage:
  scripts/setup/freeq-validate-peer-env.sh PATH

The file must be the public peer.env generated by FreeQ setup. It must not
contain private identity material.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

PEER_ENV="${1:-}"
if [ -z "$PEER_ENV" ]; then
  usage >&2
  exit 1
fi
if [ ! -f "$PEER_ENV" ]; then
  echo "Missing peer env file: $PEER_ENV" >&2
  exit 1
fi

validate_endpoint() {
  local endpoint="$1"
  case "$endpoint" in
    *REPLACE*|*PLACEHOLDER*|*HOST_OR_IP*|*ACTUAL_*|*YOUR_HOST*|*PEER_HOST*|*peer-host*|*"<"*|*">"*)
      echo "FREEQ_PUBLIC_ENDPOINT is still a placeholder: $endpoint" >&2
      exit 1
      ;;
  esac
  if [[ "$endpoint" != *:* ]]; then
    echo "FREEQ_PUBLIC_ENDPOINT must be HOST:PORT, got: $endpoint" >&2
    exit 1
  fi
  local host="${endpoint%:*}"
  local port="${endpoint##*:}"
  if [ -z "$host" ] || [ -z "$port" ] || ! [[ "$port" =~ ^[0-9]+$ ]] || [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
    echo "FREEQ_PUBLIC_ENDPOINT must be HOST:PORT with port 1-65535, got: $endpoint" >&2
    exit 1
  fi
}

while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    ""|\#*) continue ;;
    FREEQ_IDENTITY_KEY_PATH=*|*identity.key*)
      echo "This file contains private identity material. Do not use or send it as peer.env:" >&2
      echo "  $PEER_ENV" >&2
      exit 1
      ;;
  esac
  if [[ "$line" =~ ^(FREEQ_NODE_NAME|FREEQ_NODE_ADDRESS|FREEQ_NODE_LISTEN|FREEQ_PUBLIC_ENDPOINT|FREEQ_PUBLIC_KEY_B64|FREEQ_KEM_KEY_B64)=\'([^\']*)\'$ ]]; then
    printf -v "${BASH_REMATCH[1]}" '%s' "${BASH_REMATCH[2]}"
    continue
  fi
  echo "Unexpected line in peer env file:" >&2
  echo "  $line" >&2
  echo "Ask the other node operator to rerun setup and resend the generated peer.env file." >&2
  exit 1
done < "$PEER_ENV"

for name in FREEQ_NODE_NAME FREEQ_NODE_ADDRESS FREEQ_NODE_LISTEN FREEQ_PUBLIC_ENDPOINT FREEQ_PUBLIC_KEY_B64 FREEQ_KEM_KEY_B64; do
  if [ -z "${!name:-}" ]; then
    echo "$name is missing or blank in peer env file:" >&2
    echo "  $PEER_ENV" >&2
    echo "Ask the other node operator to rerun setup and resend the generated peer.env file." >&2
    exit 1
  fi
done

case "$FREEQ_NODE_ADDRESS" in
  */*) ;;
  *)
    echo "FREEQ_NODE_ADDRESS must include a CIDR suffix, got: $FREEQ_NODE_ADDRESS" >&2
    exit 1
    ;;
esac

validate_endpoint "$FREEQ_PUBLIC_ENDPOINT"

echo "Peer env is valid:"
echo "  $PEER_ENV"
echo "  node: $FREEQ_NODE_NAME"
echo "  overlay: $FREEQ_NODE_ADDRESS"
echo "  endpoint: $FREEQ_PUBLIC_ENDPOINT"
