#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Validate a FreeQ peer.env exchange file.

Usage:
  scripts/setup/freeq-validate-peer-env.sh PATH

The file must be the public peer.env generated by FreeQ setup. It must not
contain private identity material.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

PEER_ENV="${1:-}"
if [ -z "$PEER_ENV" ]; then
  usage >&2
  exit 1
fi
if [ ! -f "$PEER_ENV" ]; then
  echo "Missing peer env file: $PEER_ENV" >&2
  exit 1
fi

validate_endpoint() {
  local endpoint="$1"
  case "$endpoint" in
    *REPLACE*|*PLACEHOLDER*|*HOST_OR_IP*|*ACTUAL_*|*YOUR_HOST*|*PEER_HOST*|*peer-host*|*"<"*|*">"*)
      echo "FREEQ_PUBLIC_ENDPOINT is still a placeholder: $endpoint" >&2
      exit 1
      ;;
  esac
  if [[ "$endpoint" != *:* ]]; then
    echo "FREEQ_PUBLIC_ENDPOINT must be HOST:PORT, got: $endpoint" >&2
    exit 1
  fi
  local host="${endpoint%:*}"
  local port="${endpoint##*:}"
  if [ -z "$host" ] || [ -z "$port" ] || ! [[ "$port" =~ ^[0-9]+$ ]] || [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
    echo "FREEQ_PUBLIC_ENDPOINT must be HOST:PORT with port 1-65535, got: $endpoint" >&2
    exit 1
  fi
}

validate_node_name() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$ ]]
}

validate_socket_addr() {
  python3 - "$1" <<'PY' >/dev/null 2>&1
import ipaddress
import sys

value = sys.argv[1]
if value.startswith("["):
    host, sep, port = value[1:].partition("]:")
else:
    host, sep, port = value.rpartition(":")
if not host or not sep or not port.isdigit():
    raise SystemExit(1)
try:
    ipaddress.ip_address(host)
except ValueError:
    raise SystemExit(1)
port_int = int(port)
if not (1 <= port_int <= 65535):
    raise SystemExit(1)
PY
}

validate_overlay_cidr() {
  python3 - "$1" <<'PY' >/dev/null 2>&1
import ipaddress
import sys

try:
    network = ipaddress.ip_network(sys.argv[1], strict=False)
except ValueError:
    raise SystemExit(1)
if network.version != 4:
    raise SystemExit(1)
PY
}

validate_exchange_key() {
  local name="$1"
  local value="$2"
  python3 - "$name" "$value" <<'PY' >/dev/null 2>&1
import base64
import sys

name, value = sys.argv[1], sys.argv[2]
try:
    decoded = base64.b64decode(value, validate=True)
except Exception:
    raise SystemExit(1)
if len(decoded) < 16:
    raise SystemExit(1)
PY
}

while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    ""|\#*) continue ;;
    FREEQ_IDENTITY_KEY_PATH=*|*identity.key*)
      echo "This file contains private identity material. Do not use or send it as peer.env:" >&2
      echo "  $PEER_ENV" >&2
      exit 1
      ;;
  esac
  if [[ "$line" =~ ^(FREEQ_NODE_NAME|FREEQ_NODE_ADDRESS|FREEQ_NODE_LISTEN|FREEQ_PUBLIC_ENDPOINT|FREEQ_PUBLIC_KEY_B64|FREEQ_KEM_KEY_B64)=\'([^\']*)\'$ ]]; then
    printf -v "${BASH_REMATCH[1]}" '%s' "${BASH_REMATCH[2]}"
    continue
  fi
  echo "Unexpected line in peer env file:" >&2
  echo "  $line" >&2
  echo "Ask the other node operator to rerun setup and resend the generated peer.env file." >&2
  exit 1
done < "$PEER_ENV"

for name in FREEQ_NODE_NAME FREEQ_NODE_ADDRESS FREEQ_NODE_LISTEN FREEQ_PUBLIC_ENDPOINT FREEQ_PUBLIC_KEY_B64 FREEQ_KEM_KEY_B64; do
  if [ -z "${!name:-}" ]; then
    echo "$name is missing or blank in peer env file:" >&2
    echo "  $PEER_ENV" >&2
    echo "Ask the other node operator to rerun setup and resend the generated peer.env file." >&2
    exit 1
  fi
done

if ! validate_node_name "$FREEQ_NODE_NAME"; then
  echo "FREEQ_NODE_NAME must use only letters, numbers, dot, dash, or underscore, got: $FREEQ_NODE_NAME" >&2
  exit 1
fi

if ! validate_overlay_cidr "$FREEQ_NODE_ADDRESS"; then
  echo "FREEQ_NODE_ADDRESS must be a valid IPv4 CIDR, got: $FREEQ_NODE_ADDRESS" >&2
  exit 1
fi

if ! validate_socket_addr "$FREEQ_NODE_LISTEN"; then
  echo "FREEQ_NODE_LISTEN must be an IP:PORT socket address, got: $FREEQ_NODE_LISTEN" >&2
  exit 1
fi

validate_endpoint "$FREEQ_PUBLIC_ENDPOINT"
for name in FREEQ_PUBLIC_KEY_B64 FREEQ_KEM_KEY_B64; do
  if ! validate_exchange_key "$name" "${!name}"; then
    echo "$name must be valid non-empty base64 in peer env file:" >&2
    echo "  $PEER_ENV" >&2
    exit 1
  fi
done

echo "Peer env is valid:"
echo "  $PEER_ENV"
echo "  node: $FREEQ_NODE_NAME"
echo "  overlay: $FREEQ_NODE_ADDRESS"
echo "  endpoint: $FREEQ_PUBLIC_ENDPOINT"
